version: "3.9"

name: snpclic-dev
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_ENVIRONMENT: development
        DATABASE_HOST: db-dev
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_NAME: ${DATABASE_NAME}
        R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
        R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
        R2_BUCKET_NAME: ${R2_BUCKET_NAME}
        R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
        RESEND_API_KEY: ${RESEND_API_KEY}
        PDF_API_KEY: ${PDF_API_KEY}
        PDF_API_URL: ${PDF_API_URL}
    container_name: app-dev
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_ENVIRONMENT: development
      DATABASE_HOST: db-dev
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      RESEND_API_KEY: ${RESEND_API_KEY}
      PDF_API_KEY: ${PDF_API_KEY}
      PDF_API_URL: ${PDF_API_URL}
      WATCHPACK_POLLING: true
    depends_on:
      db-dev:
        condition: service_healthy
    networks:
      - snpclic-network-dev
    volumes:
      - type: bind
        source: ./src
        target: /app/src
      - type: volume
        target: /app/node_modules

  db-dev:
    image: mysql:8
    container_name: db-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3001:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
    networks:
      - snpclic-network-dev
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1"]
      interval: 10s
      retries: 5
      timeout: 3s
      start_period: 0s

networks:
  snpclic-network-dev:
    driver: bridge

volumes:
  db_data_dev:
