FROM nginx:latest

ARG APP_ENVIRONMENT
ENV APP_ENVIRONMENT=$APP_ENVIRONMENT

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# if the environment is preview modify the nginx.conf to redirect to replace snpclic by preview.snpclic
RUN if [ "$APP_ENVIRONMENT" = "preview" ]; then \
      sed -i 's/snpclic/preview.snpclic/g' /etc/nginx/conf.d/default.conf; \
    fi

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
